
version: 2

workflows:
  version: 2
  build-and-test:
    jobs:
      - build

references:

  restore_backend_stack_cache: &restore_backend_stack_cache
    restore_cache:
      keys:
        - v1-cache-stack-{{ .Branch }}-{{ checksum "package.yaml" }}
        - v1-cache-stack-{{ .Branch }}
        - v1-cache-stack

  save_backend_stack_cache: &save_backend_stack_cache
    save_cache:
      key: v1-cache-stack-{{ .Branch }}-{{ checksum "package.yaml" }}
      paths:
        - ~/.stack

jobs:
  build:
    working_directory: ~/stdlib.hs/stdlib.hs
    parallelism: 1
    docker:
      - image: fpco/stack-build:lts-11.10
    steps:
      - checkout
      - *restore_backend_stack_cache
      - run: stack setup --no-terminal
      - run: stack install --no-terminal --only-dependencies --jobs 2
      - *save_backend_stack_cache
      - run: stack build
